AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 
  paramName:
    Description: 
    Type: AWS::EC2::KeyPair::KeyName
    Default: 
Mappings: 

Conditions: 

Resources:
  snake-tg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: snake-tg
      Protocol: HTTP
      Port: 8080
      VpcId: ???
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 5
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckPath": "/healthCheck
      Matcher:
        HttpCode: 200
      TargetType: instance
      ProtocolVersion: HTTP1
      Targets:
      - Id: !GetAtt [ MyLambdaFunction, Arn ]
  myELBname:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - sg-id
      Subnets:
        - subnet-id
      Instances:
        - instance-id
      Listeners:
        - LoadBalancerPort: 
          InstancePort: 
          Protocol: HTTP|HTTPS|TCP|SSL
          InstanceProtocol: HTTP|HTTPS|TCP|SSL
        - LoadBalancerPort: '443'
          InstancePort: '443'
          Protocol: HTTPS
          InstanceProtocol: HTTPS
          SSLCertificateId: 
      HealthCheck:
        Target: TCP:port or HTTPS|HTTP:port/PathToPing
        HealthyThreshold: 
        Interval: 
        Timeout: 
        UnhealthyThreshold: 
  launchConfigName:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: 
      AssociatePublicIpAddress: true|false
      IamInstanceProfile: 
      ImageId: 
      EbsOptimized: true|false
      InstanceMonitoring: true|false
      InstanceType: 
      KernelId: 
      KeyName: 
      SecurityGroups:
        - sg-id
      UserData:
        Fn::Base64: !Sub
          #!/bin/bash -ex # your script here
  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: 
      MaxSize: 0
      MinSize: 0
      Tags:
        - Key: keyname
          Value: value
          PropagateAtLaunch: True|False
Outputs: